"""Emit a MITRE ATT&CK Navigator layer (v4.5) from scored techniques.

The Navigator layer JSON is the product's UI contract: import it into the ATT&CK
Navigator (or overlay it on an existing detection-coverage layer) to see
exploitable techniques ranked by aggregated VPR. No bundled web UI — the layer
*is* the interface.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from pathlib import Path

from .models import Finding, TechniqueScore

# Tenable's public plugin reference page; SC plugin IDs are Nessus plugin IDs.
_TENABLE_PLUGIN_URL = "https://www.tenable.com/plugins/nessus/{plugin_id}"
_ATTACK_TECHNIQUE_URL = "https://attack.mitre.org/techniques/{path}"

# Layer format version (fixed) and the minimum Navigator app version that reads
# it. ``attack`` is intentionally omitted from the output: per the layer spec it
# is optional and, when absent, the Navigator assumes its own current ATT&CK
# version — which avoids the "this layer uses an outdated ATT&CK version, upgrade?"
# prompt regardless of which ATT&CK release the user's Navigator is pinned to.
LAYER_VERSION = "4.5"
NAVIGATOR_VERSION = "4.9.1"

# Gradient from pale (low exposure) to deep red (high exposure).
_GRADIENT = ["#fff5f0", "#fb6a4a", "#67000d"]
# Findings with no confident evidence are tinted distinctly so reviewers spot them.
_NEEDS_REVIEW_COLOR = "#bdbdbd"


def build_layer(
    scores: Iterable[TechniqueScore],
    *,
    name: str = "Tenable Exposure -> ATT&CK",
    description: str = "VPR-scored ATT&CK coverage generated by tenable-attack-mapper.",
    technique_catalog: Mapping[str, dict] | None = None,
    findings_by_plugin: Mapping[str, "Finding"] | None = None,
    max_findings_per_technique: int = 40,
    attack_version: str | None = None,
) -> dict:
    """Build a Navigator-compatible layer dict (v4.5).

    :param findings_by_plugin: the findings behind the scores, keyed by plugin id.
        When provided, each technique's ``metadata`` lists the actual
        vulnerabilities driving it (plugin name, CVE, VPR) — visible in the
        Navigator tooltip on hover — and ``links`` point at each plugin's Tenable
        page, so clicking a technique lets you drill into its findings.
    :param attack_version: pin the layer to a specific ATT&CK version. Leave as
        ``None`` (default) to omit it, so the Navigator assumes its current
        version and does not prompt to upgrade.
    """
    catalog = technique_catalog or {}
    findings_by_plugin = findings_by_plugin or {}
    techniques = []
    for score in scores:
        meta = catalog.get(score.technique_id, {})
        comment = _comment_for(score, meta)
        # Set an explicit color so filled techniques always render colored, even
        # if the Navigator doesn't fully restore the gradient on load. Needs-review
        # techniques get a distinct grey instead of a gradient tint.
        color = _NEEDS_REVIEW_COLOR if score.needs_review else _gradient_color(score.score)

        finding_objs = _findings_for_score(score, findings_by_plugin)
        techniques.append(
            {
                "techniqueID": score.technique_id,
                "score": score.score,
                "color": color,
                "comment": comment,
                "enabled": True,
                "showSubtechniques": "." in score.technique_id,
                "metadata": _technique_metadata(
                    score, finding_objs, max_findings_per_technique
                ),
                "links": _technique_links(score, finding_objs, max_findings_per_technique),
            }
        )

    versions: dict[str, str] = {
        "navigator": NAVIGATOR_VERSION,
        "layer": LAYER_VERSION,
    }
    if attack_version:
        versions["attack"] = attack_version

    return {
        "name": name,
        "versions": versions,
        "domain": "enterprise-attack",
        "description": description,
        "filters": {"platforms": ["PRE", "Windows", "Linux", "macOS", "Network"]},
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": False,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {"colors": list(_GRADIENT), "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "needs review (low confidence)", "color": _NEEDS_REVIEW_COLOR}
        ],
        "metadata": [
            {"name": "generator", "value": "tenable-attack-mapper"},
            {"name": "technique_count", "value": str(len(techniques))},
        ],
        "links": [],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def write_layer(layer: dict, out_path: str | Path) -> Path:
    """Serialize a layer dict to disk and return the path."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(layer, fh, indent=2)
        fh.write("\n")
    return path


def _findings_for_score(
    score: TechniqueScore, findings_by_plugin: Mapping[str, Finding]
) -> list[Finding]:
    """Resolve a technique's contributing findings, highest VPR first."""
    objs = [findings_by_plugin[pid] for pid in score.plugin_ids if pid in findings_by_plugin]
    objs.sort(key=lambda f: (f.vpr_score if f.vpr_score is not None else -1.0), reverse=True)
    return objs


def _technique_metadata(
    score: TechniqueScore, findings: list[Finding], cap: int
) -> list[dict]:
    """Aggregate stats plus the per-finding vulnerability list (capped).

    The Navigator renders these name/value rows in the technique's hover tooltip,
    so this is what lets a user see *which* vulnerabilities drive a technique.
    """
    metadata: list[dict] = [
        {"name": "findings", "value": str(score.finding_count)},
        {"name": "total_vpr", "value": f"{score.total_vpr:.1f}"},
        {"name": "max_confidence", "value": f"{score.max_confidence:.2f}"},
        {"name": "sources", "value": ", ".join(score.sources)},
        {"name": "needs_review", "value": str(score.needs_review).lower()},
    ]

    if not findings:
        return metadata

    metadata.append({"divider": True})
    for finding in findings[:cap]:
        metadata.append(
            {
                "name": f"plugin {finding.plugin_id}",
                "value": _finding_label(finding),
            }
        )
    remaining = len(findings) - cap
    if remaining > 0:
        metadata.append({"name": "…", "value": f"+{remaining} more finding(s)"})
    return metadata


def _technique_links(
    score: TechniqueScore, findings: list[Finding], cap: int
) -> list[dict]:
    """A link to the ATT&CK technique page, then one per contributing plugin.

    Links appear in the technique's right-click context menu in the Navigator —
    click through to open each Tenable plugin (vulnerability) page.
    """
    path = score.technique_id.replace(".", "/")
    links: list[dict] = [
        {
            "label": f"ATT&CK: {score.technique_id}",
            "url": _ATTACK_TECHNIQUE_URL.format(path=path),
        }
    ]
    if findings:
        links.append({"divider": True})
    for finding in findings[:cap]:
        label = f"{finding.plugin_id}: {finding.plugin_name[:60]}"
        links.append(
            {"label": label, "url": _TENABLE_PLUGIN_URL.format(plugin_id=finding.plugin_id)}
        )
    return links


def _finding_label(finding: Finding) -> str:
    parts = [finding.plugin_name or "(unnamed plugin)"]
    if finding.cves:
        parts.append(", ".join(finding.cves[:4]))
    if finding.vpr_score is not None:
        parts.append(f"VPR {finding.vpr_score:.1f}")
    if finding.count > 1:
        parts.append(f"×{finding.count} hosts")
    return " — ".join(parts)


def _gradient_color(score: float, stops: list[str] | None = None) -> str:
    """Interpolate a hex color for a 0-100 score across the gradient stops.

    Mirrors how the Navigator would shade the cell from its gradient, but baked
    into each technique's ``color`` so the coloring survives a partial layer load.
    """
    stops = stops or _GRADIENT
    pct = max(0.0, min(100.0, score)) / 100.0
    if pct <= 0:
        return stops[0]
    if pct >= 1:
        return stops[-1]

    segments = len(stops) - 1
    pos = pct * segments
    idx = int(pos)
    idx = min(idx, segments - 1)
    frac = pos - idx
    start = _hex_to_rgb(stops[idx])
    end = _hex_to_rgb(stops[idx + 1])
    blended = tuple(round(s + (e - s) * frac) for s, e in zip(start, end))
    return _rgb_to_hex(blended)


def _hex_to_rgb(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def _rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def _comment_for(score: TechniqueScore, meta: dict) -> str:
    name = meta.get("name")
    prefix = f"{name}\n" if name else ""
    review = " [NEEDS REVIEW]" if score.needs_review else ""
    return (
        f"{prefix}{score.finding_count} finding(s), "
        f"total VPR {score.total_vpr:.1f}, "
        f"confidence {score.max_confidence:.2f}{review}"
    )
