"""Emit a MITRE ATT&CK Navigator layer (v4.5) from scored techniques.

The Navigator layer JSON is the product's UI contract: import it into the ATT&CK
Navigator (or overlay it on an existing detection-coverage layer) to see
exploitable techniques ranked by aggregated VPR. No bundled web UI — the layer
*is* the interface.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from pathlib import Path

from .models import TechniqueScore

LAYER_VERSION = "4.5"
NAVIGATOR_VERSION = "4.9.1"
ATTACK_VERSION = "14"

# Gradient from pale (low exposure) to deep red (high exposure).
_GRADIENT = ["#fff5f0", "#fb6a4a", "#67000d"]
# Findings with no confident evidence are tinted distinctly so reviewers spot them.
_NEEDS_REVIEW_COLOR = "#bdbdbd"


def build_layer(
    scores: Iterable[TechniqueScore],
    *,
    name: str = "Tenable Exposure -> ATT&CK",
    description: str = "VPR-scored ATT&CK coverage generated by tenable-attack-mapper.",
    technique_catalog: Mapping[str, dict] | None = None,
) -> dict:
    """Build a Navigator-compatible layer dict (v4.5)."""
    catalog = technique_catalog or {}
    techniques = []
    for score in scores:
        meta = catalog.get(score.technique_id, {})
        comment = _comment_for(score, meta)
        techniques.append(
            {
                "techniqueID": score.technique_id,
                "score": score.score,
                "color": _NEEDS_REVIEW_COLOR if score.needs_review else "",
                "comment": comment,
                "enabled": True,
                "showSubtechniques": "." in score.technique_id,
                "metadata": [
                    {"name": "findings", "value": str(score.finding_count)},
                    {"name": "total_vpr", "value": f"{score.total_vpr:.1f}"},
                    {"name": "max_confidence", "value": f"{score.max_confidence:.2f}"},
                    {"name": "sources", "value": ", ".join(score.sources)},
                    {"name": "needs_review", "value": str(score.needs_review).lower()},
                ],
                "links": [],
            }
        )

    return {
        "name": name,
        "versions": {
            "attack": ATTACK_VERSION,
            "navigator": NAVIGATOR_VERSION,
            "layer": LAYER_VERSION,
        },
        "domain": "enterprise-attack",
        "description": description,
        "filters": {"platforms": ["Windows", "Linux", "macOS", "Network", "Containers"]},
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": False,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {"colors": list(_GRADIENT), "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "needs review (low confidence)", "color": _NEEDS_REVIEW_COLOR}
        ],
        "metadata": [
            {"name": "generator", "value": "tenable-attack-mapper"},
            {"name": "technique_count", "value": str(len(techniques))},
        ],
        "links": [],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def write_layer(layer: dict, out_path: str | Path) -> Path:
    """Serialize a layer dict to disk and return the path."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(layer, fh, indent=2)
        fh.write("\n")
    return path


def _comment_for(score: TechniqueScore, meta: dict) -> str:
    name = meta.get("name")
    prefix = f"{name}\n" if name else ""
    review = " [NEEDS REVIEW]" if score.needs_review else ""
    return (
        f"{prefix}{score.finding_count} finding(s), "
        f"total VPR {score.total_vpr:.1f}, "
        f"confidence {score.max_confidence:.2f}{review}"
    )
